# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: "Release"

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**./*csproj'
    feedsToUse: 'select'
    displayName: 'Restore Packages'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '**/*csproj'
        displayName: 'Build Project'
